# plot4.R 
# This plot incorporates the plots created in plot2 and plot3 for two of the 
# four plots in a 2 by 2 grid, so I will reuse the code from plot2.R and plot3.R.

# Set graphical parameters to values for this exercise. mfrow is used to set the plot region in a 
# 2 by 2 array, with the plots generated by rows. The plot area is set to be square with pty set to "s",
# and the characters are reduced in size to 75% of their original value by setting the parameter
# cex to 0.75.


# Create the vectors for the two new plots of Voltage and Global Reactive Power
hpc.Volts <- hpc.Project1$Voltage
hpc.grp <- hpc.Project1$Global_reactive_power

# Here we set the output device to a PNG file, then create the plots in the correct order. Remember,
# the plots will be assigned to locations in the 2 by 2 grid by rows.

png(file="plot4.png", bg="white")
par(mfrow = c(2,2), pty="s", cex=0.75)
plot(hpc.Date.Time.P, hpc.gap, type="l", ylab="Global Active Power", xlab="")
plot(hpc.Date.Time.P, hpc.Volts, type="l", ylab="Voltage", xlab="datetime")
plot(hpc.Date.Time.P, hpc.sm1, type="l", ylab="Energy sub metering", xlab="", col = "black")
lines(hpc.Date.Time.P, hpc.sm2, type="l", ylab = "", xlab="", col = "red")
lines(hpc.Date.Time.P, hpc.sm3, type="l", ylab="", xlab="", col="blue")
legend("topright", bty="n", lty = 1, col=c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(hpc.Date.Time.P, hpc.grp, type="l", ylab="Global_reactive_power", xlab="datetime")

# Now clean up by setting dev.off() and putting the graphical parameters back to their default values
dev.off()
